---
title: "Opioids in NY"
author: "Julia Thompson"
date: "1/3/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(arcos)
library(readxl)
library(plotly)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Description of Data


  **amfAR Data: [Distance to Treatment Facility](<https://opioid.amfar.org/about/sources>)**
    amfAR is a non-profit which publishes data related to the HIV epidemic. The data set we utilized contains the average distance from each county to an opioid related treatment facility. 
    
  **New York State Health Data: [Opioid related Treatments and Deaths](<https://health.data.ny.gov>)**
    This data set details opioid related treatments from, including both inpatient and outpatient treatment for opioid diagnoses from 2010 to 2015. The data is then categorized by county, year, whether the county is urban or rural, and the insurance of the patient. An additional data set in the New York health data which included the number of opioid related deaths from 2003 to 2017 was also utilized. 
  
  **ARCOS Data: [Pills Prescribed by County](<https://github.com/wpinvestigative/arcos-api>)**
    The ARCOS data set is published by the Washington Post as part of a database which tracks opioid prescriptions from manufacturer to patient between 2006 and 2012. We utilized the data related to the number of pills prescribed to patients in each U.S. county, filtering for the counties in New York state. 
    
  **Government Data: [Medication Take-Back Facilities](<https://catalog.data.gov/>)**
    Finally, we used government data which provided the location of medication take-back facilities. This data was limited to counties in New York state, and the distance was mapped against opioid related deaths and treatments. The medication take-back facility data was collected in 2017.
    
_This project was done in collaboration with other students._