---
title: "Plotly Examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Now this is the plotly page

Testing let's make interactive graphics
You can add "code_folding: hide" to hide the code

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

## For homework:

```{r}
data(rest_inspec)
```

Plot 1

```{r}
rest_clean = 
  mutate(rest_inspec, grade_date = as.character(grade_date)) %>% 
  separate(col = grade_date, into = c("year", "month", "day"), sep="-") %>% 
  select(-building, -camis, -street, -zipcode, -phone, -record_date, -violation_code) %>% 
  drop_na(grade, year) %>%
  filter(grade == "A" | grade == "B" | grade == "C", boro != "Missing", year != "2012")


rest_clean %>% 
  mutate(
    is_a = (grade == "A")
  ) %>% 
  group_by(boro, year) %>% 
  summarize(
    proportion_a = sum(is_a)/n()
  ) %>% plot_ly(x = ~year, y = ~proportion_a, type = "scatter", mode = "lines+markers",
    color = ~boro, alpha = 0.5)
```

Plot 2

```{r}
rest_clean %>% 
  group_by(grade, boro) %>% 
  summarize(
    n = n()
  ) %>% 
  plot_ly(x = ~boro, y = ~n, type = "bar",
          color = ~grade, alpha = 0.5)
```

Plot 3

```{r}
rest_clean %>% 
  plot_ly(x = ~boro, y = ~score, type = "violin")
```
