---
title: "Julia Thompson"
output: 
  html_document:
    toc: true
    toc_float: true
---


5 West 101st St New York, NY 10025 | 336.687.3514 | julia.thompson@columbia.edu 

### EDUCATION

**Columbia University Mailman School of Public Health**

Master of Science, Biostatistics	_Expected May 2021_

Current GPA: 3.667

**University of North Carolina at Chapel Hill Gillings School of Global Public Health**

Bachelor of Science in Public Health, Biostatistics _May 2018_

Major GPA: 4.0 | Overall GPA: 3.467 | Dean’s List: 3 semesters

### EXPERIENCE	

**Columbia University Mailman School of Public Health**, New York, NY

Teaching Assistant: Statistical Computing with SAS _August 2020 to December 2020_

* Lead groups of 10 students each week to answer questions regarding course material and homework

* Hold office hours once per week to assess and troubleshoot coding problems the students might have

* Grade and provide feedback on homework assignments and midterm exams for the class of 35 students

**Global Healthy Living Foundation**, New York, NY

Data Science Intern _December 2019 to September 2020_

* Cleaned, analyzed, and interpreted data for chronic disease studies using SAS and R. Completed 15 short-term and 10 long-term statistical analysis projects during my internship, ranging from building regression models and performing hypothesis tests to creating presentations and reports

* Spearheaded weekly dissemination of study results through email, webinars, and infographics to key stakeholders

* Wrote several procedures in MySQL to combine results across patient platforms and improve insights

* Contributed to writing and analysis of various manuscripts for publication, including one currently under review in Arthritis Research and Therapy: _Marijuana and Cannabidiol for Medical Use in Rheumatic and Musculoskeletal Disease: Patients’ Perceptions, Behaviors and Health Information Needs_

**Corvid Technologies**, Charlotte, NC

Analyst	_June 2018 to June 2019_

* Created a cash flow analysis tool for predictions and insight into the company’s accounts, automating email updates to the CEO and CFO and reducing the finance team’s time investment by approximately 15%

* Identified inefficiencies and developed ways to streamline internal accounting and finance processes

**University of North Carolina at Greensboro**, Greensboro, NC

Research Education for Undergraduates in Mathematical Biology _May 2016 to August 2016_

* Developed and tested an algorithm for detecting significant copy number variations across patients using R 

* Presented research findings at the International Conference of Undergraduate Research and the International Conference on Advances in Interdisciplinary Statistics and Combinatorics

### LEADERSHIP AND ACTIVITIES	

**Carolina Cystic Fibrosis Friends**, Chapel Hill, NC

President and Founder	_December 2014 to May 2018_

* Founded and managed a club that partnered with UNC Hospitals and volunteered with adult Cystic Fibrosis patients, visiting 8-10 patients and families per month, and seasonally decorating the waiting rooms

* Raised over $30,000 for Cystic Fibrosis research through campus events and community partnerships

**Student United Way**, Chapel Hill, NC 

VP of Marketing	_October 2015 to May 2018_

* Designed and enacted advertising campaigns to promote the club and service opportunities for all students

**Study Abroad**, Dublin, Ireland 

Student	_May 2017 to August 2017_

*	Studied genetics and Irish mythology 	

### TECHNICAL SKILLS

R | SAS | SQL | LaTeX | Microsoft Office (Excel, PowerPoint, Word) | Visual Basic

### RELEVANT COURSEWORK

Biostatistical Methods | Data Science | Epidemiology | Statistical Inference | Causal Inference | Statistical Inference | Sample Survey Methodology | Relational Databases and SQL | Randomized Clinical Trials | Computational Methods for Genetics and Genomics | Longitudinal Data Analysis | Probability Theory | Multidisciplinary Perspective on HIV/AIDS | Statistical Computing with SAS
